name: Android Debug APK (icatch_camera_plugin/example)

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '.github/workflows/android-debug.yml'

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter version
        run: flutter --version

      - name: Pub get (example app)
        working-directory: example
        run: flutter pub get

      - name: Build Debug APK (example app)
        working-directory: example
        run: flutter build apk --debug --no-shrink -v

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-app-debug-apk
          path: example/build/app/outputs/flutter-apk/app-debug.apk